### PR TITLE
(SIMP-5502) Refactor due to breaking changes

### PR DESCRIPTION
**Pull request by trevor-vaughan**
- Refactored the module to work with Puppet > 5.5.6
  - Puppet 5.5.7 broke the Type/Provider interface in the 'group' type so
    required an emergency refactor
  - The offending commit chain starts around https://github.com/puppetlabs/puppet/pull/7111

SIMP-5502 #close

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
:x:  https://gitlab.com/simp/puppet-gpasswd/pipelines/34218048

**Comment by trevor-vaughan** [comment]
:x:  https://gitlab.com/simp/puppet-gpasswd/pipelines/34221324

**Comment by trevor-vaughan** [comment]
:heavy_check_mark: https://gitlab.com/simp/puppet-gpasswd/pipelines/34227179

**Review by op-ct — APPROVED** [review]
:eye: :+1: 

There are strange new methods like `shouldorig`, but the logic is effectively the same.

**Pull request merged**
